github-token: ENC[AES256_GCM,data:qgX9Vk4HB817KP1QHTWvY90S+aN9QKhQF7yZ7KKAf9sHWxAWPAmQ3A==,iv:uucQ4q0ss+bIt2yLBoiqgwR7Vsk5ZeFR3mCB94Xo+Fo=,tag:KAu+yCbILHFu9ptI00mvnQ==,type:str]
sops:
    age:
        - recipient: age1v93l5pvd9pwlr9z04daa00wh2wan6ycu9ts8hn6p77gasgax256s6c6qg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUnMzTlZSYmtCOUFTMWFz
            U21YMHhKNHlkcThQMG5jTG5TNFlrUXVwRlZvCjVHdXFacktxNk9INjIwNWhmTWZQ
            dXM1TmFBSnlScUFvZ3AvdFJSbHc3T1kKLS0tIGQxcmlXMUNkNmVuNHhZYnRpRWox
            a3U5RlcrbTFLTllYRGhQYnNmNG95RkUKGWt2iFblTJcnC3E5IqZO5ItDm7q37unJ
            O+Vybn+zt+0QAjB72VgokbcxJhtCyR8RCMtNUZjlRIv14NBRbBBGWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T20:22:03Z"
    mac: ENC[AES256_GCM,data:5fKsSMANvSL8bbjxRuOy5mUuzf6n6+RDokYElIcAYNAtbUt0aZEuhO6vauNB7bbvHx/vNh+4JDHzIwOu46BZm0jzAF55lLGmp9YBRbK8m7qRXsaLHD/y+G+HdABje7jj74ZAoDRf37Qj363GrfiJC9kAWP8J2g6WCFvO+iIRNz0=,iv:lwgiJw9hfxzmsdzt2rsde/LnIInGo1OPBr3vhF3yJ18=,tag:D8nJMCTJYbISNlYujYpzfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
