wifi:
    ssid: ENC[AES256_GCM,data:Xfxp298pnfOxIabNkd0=,iv:sD82WVF50Bl7y/ow4/s56S1JE3g7y7+6gel4bcIpjc8=,tag:ToWij05WLTZudNdfL4jytQ==,type:str]
    password: ENC[AES256_GCM,data:xhRVYEYlldepZo9Z,iv:qPBBxqNCPlx/BfrVFpoTiHvCDN0fRBcxuic4b1GY2Io=,tag:JJ2UsyCZik22ER1qdl7uCQ==,type:str]
sops:
    age:
        - recipient: age1a868fs5jjehx032kq7sryz3sjfzhkk79q2clqx8f4zawpfrlp9sswgr9fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBockZseWpMS1pVZUN4N1pz
            Y3BDVzBVekt6Q0NHS3lDQTFjKzFHS25vQ0FnCkxNZkpiM0NBUGxXQUgyQmhYNm5V
            bVhLdHRCNkFQMFhUaXkwdkZpaGtYREkKLS0tIHlhWDdJS0ZtcURLZ1lFbldtSDl1
            eFR0UmxtRDdHSXpSRGRRaDc4YmMzb1EKzAsBluTNp3//UHgrxxHTdtvEepY0DEmI
            h2bCa6XFXe/smOXPB3RVlTkm8DsWehR+T+4UcZ9cao3/8pWi2+JfXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v93l5pvd9pwlr9z04daa00wh2wan6ycu9ts8hn6p77gasgax256s6c6qg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRTk3QnBpVlNzSnlFRWQ5
            SXNvRFgrd3dxMjNNTUlwNTE5cHJLMTRYaUhBCjNDQkY3L05EWkFBMnp3b0s0MjNm
            eFdiK1MycG9hZGFId2gwWG5tUkh6NUUKLS0tIHlNYmpIL1NETllEeGFkYXdnSHhn
            ekRUMm5UcGR5Vno3bFdxMlcyVXdNQUEKV2uzm2ObSgNMS+NnN8QxU/xPZ9MydbZZ
            XK9VPmWXcNY/Hmk+bQinnvSVcmhe2EHQJ9OL32tlaBewb/BsXth1ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T16:56:27Z"
    mac: ENC[AES256_GCM,data:GXYoZxO0jW4fOhr2qzc5B5Gn8aRqyDWSmSd7WDOatn/G/chkyxg/FyzheVO9aXiq0Wav63ilU3cHpuV2janprILudhLH2bLBwoAnbUouGn8wCdViK26ilnQhPYO1d0cP9GR1oAFRXeBzO4EKMXgmjsuqyFHHPArmKfoOZXUVV1c=,iv:bMEbARKf4ce39sl7Re8mUk/sjFRqex0Ay9lrfhMjRKY=,tag:YVeNMuJGUu0W5KTV76Ch8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
