wifi:
    password: ENC[AES256_GCM,data:xhRVYEYlldepZo9Z,iv:qPBBxqNCPlx/BfrVFpoTiHvCDN0fRBcxuic4b1GY2Io=,tag:JJ2UsyCZik22ER1qdl7uCQ==,type:str]
passwd:
    alex: ENC[AES256_GCM,data:i4LouZjv/IqH+Vz23PgmfSGLx12MbSpniFI5oOQ3QzPlTDiVQpGqpPL3i53du/kFz1AWGSpb1orRiV0DsmhK1thnHafZn4nbZA==,iv:179w/hbHoIRLPLDFnPjckLLdErlRXTIelyQWLvK7Syo=,tag:K/R1wmJ3hRI+//iudE87yQ==,type:str]
ddclient:
    domain: ENC[AES256_GCM,data:jb31lpT5xb9ICKKEVB4=,iv:FfSfOeSPaiW1vklQcwVBI+8AVUgQ+NFeUSSapf0RpU4=,tag:GYkx95ax8sL0bumMD/DkLw==,type:str]
    password: ENC[AES256_GCM,data:N79BB+it+79CDtIuJsNHox+ySpam+pFTqD/UKwASuFI=,iv:rrwAaQ0WAggKAtrWToY8RzP2COtjL3zBK6W+quFbHkI=,tag:o4AxLmRHlDjn+VjvtrEsGQ==,type:str]
prefect:
    htpasswd: ENC[AES256_GCM,data:h0/43VCrHer+LroMFboUc58mu5yOlAZsz/kLtzS05O4Mi7yiRXDRNqKUFOfBU2WwUlHLHBvXCGXG5lFB00xUfilw,iv:l8IdsEbETemZpl7VtmuGgg9EokcLU3S2Z79wmZTR03A=,tag:JePO44czZsitCP9VkGlKZw==,type:str]
wireguard:
    server:
        privatekey: ENC[AES256_GCM,data:x0d3wUYXiHINworLn7H5Pk0Yy6QrQZUqvnhdGV61KzGkcxA2rHyNsAUmo5c=,iv:DnCMN9YnDZ1/OeCQ0kKURlmZNCrRNZJ02h1xqVtuDco=,tag:bPdWVPmAgK0uY3nWYRE22Q==,type:str]
    peers:
        alex-iphone:
            psk: ENC[AES256_GCM,data:1RIBeuqgVlNjcNTuFg3n1g7envyE7VbOingtYZ1wQYBorV7yYAVan4bPeBs=,iv:kareyEvvIyRQlerhKvGEwN2gHO0tDzP2gsJsKBxZN/Q=,tag:qRj1IuQRBNe8QvpOzo23Gw==,type:str]
            privatekey: ENC[AES256_GCM,data:qe6wqL2atEAC6ee6YMTcznyRhcQrZY0/1aqOFBZc59jx3r3d9puiIUllfyc=,iv:mE4s5o2jqkSKOQb4Jv0BaO2CnmZwbXQLQFOqy7+jIu4=,tag:WVbud3rde8N4E2Xj2qMrQQ==,type:str]
        alex-ipad:
            psk: ENC[AES256_GCM,data:ali1rCNEQNjBZvNDA2B9Xhi/YDgoIdPTu6zDSydpKstb5F1HzWp4d5Nz1RA=,iv:voGmmmTHAV91HIjioWP8nyVx6ZGO/h4omvzOqhLaIu8=,tag:I0ajr4lbLNJet30vMBENXg==,type:str]
            privatekey: ENC[AES256_GCM,data:2ola7iK1sf1HLeN+hLjLpxePtZSiWfiGW5tvfuCwJE1QyXj/ey4+GOKhS+E=,iv:GpDREvUWi3txoACYJ++AO2o11u1EYQaTRQU/Qf1s3og=,tag:mjKhaMC0Z7/ETGPMLraRLw==,type:str]
        alex-macbookpro:
            psk: ENC[AES256_GCM,data:FJErnNVQO2nOFZ633NOP/AiOUMtkkgT6e/tl0wjH9dwkZZWEPjnBypRAjHg=,iv:Ih58z4l24qmhKBdQKT4pLc19Ou8xg4249uNRbrHL7To=,tag:AQZ+vhWQyb7d9gGon47zhg==,type:str]
            privatekey: ENC[AES256_GCM,data:e6ZxgIxKlXuw/8iQIpUiKtP8bhDpwQPVui9XcjWDEc/3aeniF+FhdbdqUX4=,iv:wPBOvfXDe2tqawqb7xiguer6wXCO/YLnnIq0Pj/+814=,tag:VRxzN/GoJJFe+oQWtjoydw==,type:str]
        mubin-phone:
            psk: ENC[AES256_GCM,data:w5jEXwNI46F0InhUfRCuQmJ/Jz779egygsvVo/+76ZNatFdUjK9Lw3zghTw=,iv:kmDtMq/3jPe/X8Wr78w8PbYmsKwSJMnAENPSb8ufCg8=,tag:yJWUveVpOw+B6iw3BFIbIA==,type:str]
            privatekey: ENC[AES256_GCM,data:zYEl77ccOQubA/uQbEOBJi5N7YUW/Thm9hCUxTa2ROqbfvc2iUnmxHB+Md0=,iv:EB44hwifesxvMSYZD5AEj0futvNC6KTu4rpMbFARUuc=,tag:UDgYL6mwFSwl2F3w8RGeNA==,type:str]
        mubin-laptop:
            psk: ENC[AES256_GCM,data:vZhFxiaI+emoLkoLfZNJar6Zk70fyCW8Sj/UcaeiI9ftexY1FtBeY/Azx0k=,iv:bJ0eBqwdLkpqNGgXUXWP6szIS6eYph8ny64EmSp+ITA=,tag:T1/tx9ztmg9XjHrZr9Ca9w==,type:str]
            privatekey: ENC[AES256_GCM,data:11lcQCF/PD3fSJ42k/GjAj1h9zdDbz1VQYgkB5eWYdF26k5UrceS2DHrOUs=,iv:zqH80gkS7Ee0XQzeMO2dq1BSmahJNNvtTPox7H+7imA=,tag:BDI2/5gisUTCe8aei7JPvA==,type:str]
sops:
    age:
        - recipient: age1a868fs5jjehx032kq7sryz3sjfzhkk79q2clqx8f4zawpfrlp9sswgr9fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBockZseWpMS1pVZUN4N1pz
            Y3BDVzBVekt6Q0NHS3lDQTFjKzFHS25vQ0FnCkxNZkpiM0NBUGxXQUgyQmhYNm5V
            bVhLdHRCNkFQMFhUaXkwdkZpaGtYREkKLS0tIHlhWDdJS0ZtcURLZ1lFbldtSDl1
            eFR0UmxtRDdHSXpSRGRRaDc4YmMzb1EKzAsBluTNp3//UHgrxxHTdtvEepY0DEmI
            h2bCa6XFXe/smOXPB3RVlTkm8DsWehR+T+4UcZ9cao3/8pWi2+JfXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v93l5pvd9pwlr9z04daa00wh2wan6ycu9ts8hn6p77gasgax256s6c6qg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRTk3QnBpVlNzSnlFRWQ5
            SXNvRFgrd3dxMjNNTUlwNTE5cHJLMTRYaUhBCjNDQkY3L05EWkFBMnp3b0s0MjNm
            eFdiK1MycG9hZGFId2gwWG5tUkh6NUUKLS0tIHlNYmpIL1NETllEeGFkYXdnSHhn
            ekRUMm5UcGR5Vno3bFdxMlcyVXdNQUEKV2uzm2ObSgNMS+NnN8QxU/xPZ9MydbZZ
            XK9VPmWXcNY/Hmk+bQinnvSVcmhe2EHQJ9OL32tlaBewb/BsXth1ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-19T18:00:52Z"
    mac: ENC[AES256_GCM,data:S6hNVd87fgdRZ6iXDwAFrq0UYmy1cd4aSefbqbtJG+ZCUcjW9FBitoVEoe7oxan4qTJ5i9mqoQduS0Kjw+7pvT9T/qqE2Ab3nV6G8y5rSaPYY1ivP85BZ4NdUoapbNpUmEdWQTdCW42AmW4y/OOILYjwgCuXfweqqNugO2QXlDA=,iv:uTw6+YXffvD1Ni3CnkjtIFnHkh6SGSEaVQsY+TifPS0=,tag:3nIoc9fkoD1MjDdRmAZtbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
