prefect:
    user: ENC[AES256_GCM,data:29mK67Q=,iv:sf3r2im0tuUW0TDw9FxLjA0oct8mGsCurjXnr83N0X8=,tag:ywqJtTNGVbeSpj425VEe+w==,type:str]
    password: ENC[AES256_GCM,data:e0nMjGtZi4n6QClBXtYc,iv:6oTWUbfcNLhq9w/Zg3TNAqiJAHLHqFVegQX48x7UX3c=,tag:7XU7/06N23Yayy49i8+kVQ==,type:str]
sops:
    age:
        - recipient: age1a868fs5jjehx032kq7sryz3sjfzhkk79q2clqx8f4zawpfrlp9sswgr9fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NHJpYkRXM1QyVnpobTEr
            OFhsMWNSNzJLVDFiYXJBa2R6QkNDem51VHlJCnVqMGFEcGEzTnEzSWMwNDBUazZW
            ZnQ3QjVmemU5K21ZbHdKNm5UbWZjMm8KLS0tIDRsZE1uTUFaRkNDMG5ONXhEQTNl
            ZEJxS0lCUDR0U2syM3dIbUVhR0NWN3cKUvPLJ9HtpVzTBKiZFdC7i8V3cFxr+Fcz
            iFb+bx2djGXE9nhJNL6cYP4zhkX94MuzcG+hibvIs2kRnnnik3Wb+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjcu9h7rk0m44dzgyfwtyvajm2z6epscva5g0va8d9k8lz4m0fgqyu0rr2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VHhQUlgvNkRnL0k5cmlu
            QUd1VzQyZzJjSDlYRlorLytHbGFhbTMzekRFClJJcFN6OTFrYU93aE9peWZTL3Br
            UGVNQWkxRGtJWXRGdU42dmd2OXhweDAKLS0tIGwxUitWSUluUk1BL1VQQXZvcEVX
            U3Jlbm94cXY4VXF2SmFKa0tLWkI1SXMKWPedQWkssFD0FYTX/eVnHFSpF/E5M1q3
            QebYs1oCBgJGhvvI1cJU2fOWLkzLvd4VeNs/TtVnqW4sdsDuUhjZfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T15:41:21Z"
    mac: ENC[AES256_GCM,data:nrLQIwuZ3Juta1CXESpTkf/gX89HD5TFo6ET8A/q+C6pPenLZErXI9mqBt4taiaKX7blQNb2RbFR0bcGp2Gvfp8ocuUor0wz2Hbt0GTLybyxmZR1/yt5xclfbVCmf3c5ESO4o1ArS8HOqdfDrJwSeA20j/hqmoi6FwVHxn6qq6Q=,iv:uQtUP5PT2rnpZjcpzVVXxWAyKRxCHhVuaumDY2bHKgU=,tag:KIfbO5t8R99b3FIEkiO6Kw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
