prefect:
    user: ENC[AES256_GCM,data:29mK67Q=,iv:sf3r2im0tuUW0TDw9FxLjA0oct8mGsCurjXnr83N0X8=,tag:ywqJtTNGVbeSpj425VEe+w==,type:str]
    password: ENC[AES256_GCM,data:e0nMjGtZi4n6QClBXtYc,iv:6oTWUbfcNLhq9w/Zg3TNAqiJAHLHqFVegQX48x7UX3c=,tag:7XU7/06N23Yayy49i8+kVQ==,type:str]
icloud:
    password: ENC[AES256_GCM,data:2PJ7ewdGFS8ZW/hvGT9zBxLZNQ==,iv:yuOv32UW5yokmL7rjGR6j9/dV7Y69e7nwVuz0YMrKCk=,tag:KalB+a2rP33xPDQerKwAjg==,type:str]
ssh:
    nitrokey-stub: ENC[AES256_GCM,data:An/oal2TQk1zJgzv17CyjVyQdCzc2rVkMYOPKNIDXlfGwFTUZwstSCQOB0M//IYckHGn/3sC/6AxgjwWTZaoqO1vu9LmLP70j0NdPZHUjFZMh8FQ3FlrwJbGVw4HTK13oJ0ynpSZvuSe/1F1ja4tvsnKzm04r/A+PTrzZnEiTIR4nSzcFGpggUM6CrEsBzL2m9XN5pYfa9r0C7KQeIVM1+YZiwH5cYIt62y6TsUrrOH90Is8taq9ADogcdpsfwrwSqsADfXO6o28POUv9bKDrEGwMMSmppZSkgfiNX2b7LQDYhJ/kPhTH4043p0z4htUa0ECR2CLXEK5umn+cqHKPCSGNQbg93KNtrbBBAoTIMko0PZUxtFT23XoFqD7RhRnVX1YvA3r0Ngwr7PHPrXCsTfFhRCE5QwICCsxnPhq8KjGD+Yn/cZgXtRkthiY1GS+ErWUde8C4BI5ovNDCGYiajjPCG+pzZq/ZUZ+/VCEUdYFuhpvGnVzinZWd8hTc208vXUjK7i7CAmrK7iUGP2+wWbTh8xa6OZ3VsNVzc/NZGqloF9UMOeUDAy3irlAtcDXqcOAxRWF4SAw8kmAXGVHhZg2hWY7jrdV54Eb+t0Vov2WuEntMtaBklT0i1t5HOVPOZijQ6zDkrK16Dtnp3GkEwy8+J/OKkEGZ35DrB2heN9QILBN5O4kKN0aPlm1H4BCT501QuTEfq3XLx96Aih9zI3DGZBA/xBq3d1jyFQWiwBXI1meWdhNRFg0NbhBOW7J5H2Q35756SoCR2ZK56/bsgty9y260zscUxuf/eQV/gDrKh3jX7E=,iv:xUVJTP509uHRDjM7Eg7cy0W+Rv1Vtho0SkiTJqcjHc4=,tag:FpmCg4+tJ2+VLszHNCAWiA==,type:str]
sops:
    age:
        - recipient: age1a868fs5jjehx032kq7sryz3sjfzhkk79q2clqx8f4zawpfrlp9sswgr9fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NHJpYkRXM1QyVnpobTEr
            OFhsMWNSNzJLVDFiYXJBa2R6QkNDem51VHlJCnVqMGFEcGEzTnEzSWMwNDBUazZW
            ZnQ3QjVmemU5K21ZbHdKNm5UbWZjMm8KLS0tIDRsZE1uTUFaRkNDMG5ONXhEQTNl
            ZEJxS0lCUDR0U2syM3dIbUVhR0NWN3cKUvPLJ9HtpVzTBKiZFdC7i8V3cFxr+Fcz
            iFb+bx2djGXE9nhJNL6cYP4zhkX94MuzcG+hibvIs2kRnnnik3Wb+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wjcu9h7rk0m44dzgyfwtyvajm2z6epscva5g0va8d9k8lz4m0fgqyu0rr2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VHhQUlgvNkRnL0k5cmlu
            QUd1VzQyZzJjSDlYRlorLytHbGFhbTMzekRFClJJcFN6OTFrYU93aE9peWZTL3Br
            UGVNQWkxRGtJWXRGdU42dmd2OXhweDAKLS0tIGwxUitWSUluUk1BL1VQQXZvcEVX
            U3Jlbm94cXY4VXF2SmFKa0tLWkI1SXMKWPedQWkssFD0FYTX/eVnHFSpF/E5M1q3
            QebYs1oCBgJGhvvI1cJU2fOWLkzLvd4VeNs/TtVnqW4sdsDuUhjZfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T20:46:40Z"
    mac: ENC[AES256_GCM,data:Gi0aNZqXSi+ek7gw521DqptPBLnC2MNY4HG0A+L9a/H4GPv8QIBNU6VBbP5qsGE6RlUcL4IVDUQHRx4pfrX6Zhgl5RB2LDMSwefrxYm64I96juXvTP2O7L6nYfNPeRVmrESz5/wg+BCIr0gg3gBLLBXPc9+gUoQK7S5KZqKWDY4=,iv:yXPNFsvDafeKAsupQ9z7/Qg+wJVod+NsdTU4fSmWnJA=,tag:9MGowVig/mGR2pyaYR2/Eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
