user-password: ENC[AES256_GCM,data:LBTw/oVQS+hnrSxQqS+C48UUXhW0jr1ytTuHpb30HD8NhFrd11Cq4CTL+kN8oaNbJuFaXQejVGStFkIZbzTUr0domQBlGXpacQ==,iv:tSE8SMSUZRROj7c4Sx34C2ap++4nGz8HHt6aFBNPDPE=,tag:yrzWD8Yxb4fBxqSk+MGpGQ==,type:str]
private-key: ENC[AES256_GCM,data:HD/fYbAuO1t/QHA6IKCeLNHKb32EmsfSGBmRHBpGp9n9NBPeJTTbN4rReg9HaSVJ4+Qrt3lnJLGCImwWNKUieTBd5KqMopnirkqQQfKGYX9IfdBOrRUHGBEL7HgSUI2dia4S1JcOYHiS8Fdlhe2IIFHxoNgVxnMLow29QO8xOxZRQytofP9ThzpC0v3GaU3BMlrMKK9XxuL+ffbLunA0iAqEa5B0KNPnwqkYn9JwNlaF9VDX8YLVq+AIpfKDueVbE5rKuReZ5jrGg7R98c0ReEZAkjq/58U7fi1WtMIAnJctAzzUUHiPg5Or1VdBkvwkq4ksLlsB80j5Ic29uNZFgNRAbrenDu2mYvWWrDontKRF5F86IfyI6Lc3wJc0Te3QRb5uW7l6qeRRDp5lkHBjbOs9bTj/ax3aDIdVTgnw8HaM6nbjvluYzLAeZR95h7Kgs6to+9pqqHaISPStOWHrAeOkuFuC3RHwKrQ6UgRsC5ovgZiS+mjDD1zVcISh0+Ttm01R3tfqEIqX6vz+gTbqfK/Hb36v4l0WIyUXY8iv+z5ptCo=,iv:AiOrYCghYa2vHh2M1/wXDXgThzQkH7UO0ry5oT4VQH8=,tag:W0tIZ6HSoAzCdLzRAWfcwg==,type:str]
sops:
    age:
        - recipient: age1wjcu9h7rk0m44dzgyfwtyvajm2z6epscva5g0va8d9k8lz4m0fgqyu0rr2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY1lKOElueGNrUXZXUS9o
            YjU4KzlpekpTVk12Qk9vT2dPZ2tHc2xDb1RJCjVENDlUczZDaWFNcFZMSjJvSTNM
            cEtLc1FHYjF6ZGZoakdsWTZNUEpkd0kKLS0tIHhIdHdESnNWc2JGc0VjcEprMVhq
            aHMyMmFEMnJrakVKOHBGdG84UERoZ3MK9m7SsUGcEW3VuhZCvI4LSQoygEowZnhN
            rE9iwG17IZRqffHRCwkNYUQa+QahrCoxoAuOpekusGrVa0hjL1wDfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T20:27:30Z"
    mac: ENC[AES256_GCM,data:+gq+d2hwQX3EOGA95o47x7O0T2Vvg7gX87BXCeD8nEwCFVlnn8M9ApRZbys6n1LVhFlRsBpF9ZBu4ZNq85gsQXes9B++c0j1zkEnjR0g41reh1tcfEhkgNi2Nd9wFL87pxbV3SRCGqPUAtmjyZODiAebXnPmLUAxRfpQkmboISg=,iv:22cx20PVZJC7HxmFVp27IJAm5SF2Hv9d+Z7aFY6A1Qw=,tag:TN9advUFKlGX2OkojN6iuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
