wifi:
    network: ENC[AES256_GCM,data:0xomctEoMFHlI6vVFlQ=,iv:KlKLzFjnPVF5Dw8PY58hgHAlvDVM3QBvgVAYjH99rfQ=,tag:K4kC5Gwb88kNOl9n3shMHQ==,type:str]
    password: ENC[AES256_GCM,data:xhRVYEYlldepZo9Z,iv:qPBBxqNCPlx/BfrVFpoTiHvCDN0fRBcxuic4b1GY2Io=,tag:JJ2UsyCZik22ER1qdl7uCQ==,type:str]
passwd:
    alex: ENC[AES256_GCM,data:i4LouZjv/IqH+Vz23PgmfSGLx12MbSpniFI5oOQ3QzPlTDiVQpGqpPL3i53du/kFz1AWGSpb1orRiV0DsmhK1thnHafZn4nbZA==,iv:179w/hbHoIRLPLDFnPjckLLdErlRXTIelyQWLvK7Syo=,tag:K/R1wmJ3hRI+//iudE87yQ==,type:str]
ddclient:
    domain: ENC[AES256_GCM,data:jb31lpT5xb9ICKKEVB4=,iv:FfSfOeSPaiW1vklQcwVBI+8AVUgQ+NFeUSSapf0RpU4=,tag:GYkx95ax8sL0bumMD/DkLw==,type:str]
    password: ENC[AES256_GCM,data:N79BB+it+79CDtIuJsNHox+ySpam+pFTqD/UKwASuFI=,iv:rrwAaQ0WAggKAtrWToY8RzP2COtjL3zBK6W+quFbHkI=,tag:o4AxLmRHlDjn+VjvtrEsGQ==,type:str]
htpasswd:
    adguard: ENC[AES256_GCM,data:5gGrOhrRyENiTll07UlQfDeZwsXB3VTzqcvfhhd21z3vf9TI+9MqS4bJr5B/ieXt74PaHVXpBprnawmGlA/rA/0s,iv:xiNCEpOg9XXjqZkYts+K1kRSqOcIHSL7uAfqeQTPgxo=,tag:sJ4Z0/WGv7rg1JDfGuohhg==,type:str]
    prefect: ENC[AES256_GCM,data:jVCx6wSErcQcHiSyKw/RWpZiuoDSWTf3oaO8xOZXr2IJQSIr+/VgQrpONxOGqtFdri09qL2KF2IH2OrBD68xE+GA,iv:T2piviiZOMXx4On816TJkdp6CUi/tbwTmq1fwZ1eFdE=,tag:68FW4/0WjOws+k2JVFW0Kw==,type:str]
mailjet:
    token: ENC[AES256_GCM,data:yz0s23KhpDpm6jeWkdlA+1yIrgG5SW426Jb5Zm0gDmQ=,iv:LBHOrgDzOCsYa5SXg19YqA+0Y5tsf9e9sUnsvxhKDec=,tag:Weeu4sUNkZXNjMfqynMTJQ==,type:str]
    secret: ENC[AES256_GCM,data:Xo78ubgVRhfvwX+BS5khTAkDB5Ok+7TCUd7DN5JqWKo=,iv:IiWl2eLP4pOMrnRLbsvyM6zfA7K2oqUK4mLpRAwW3Fw=,tag:3lcP2Kr5EFYHv/jHvtcjDA==,type:str]
nextcloud:
    admin-pass: ENC[AES256_GCM,data:wXpq8/f8WgPNjjowGTmU,iv:wSL+6GH6szmqAyUUibUeIBlMIUqWhnNDk4wRVEC6gK4=,tag:NPn5EfeQ0euI8QOpDlmgqQ==,type:str]
wireguard:
    privatekey: ENC[AES256_GCM,data:03r2uRklUzztYcNBXzhf3T0hQJ9yy/3ZqGxwW3f4oCQFrAal7QY3w+FMIZE=,iv:6Gps7nxveJrNvFrOa09BjB69a1p1Ef0akaadaRTzZB0=,tag:HxlYta9+2m+CzIq25skS1g==,type:str]
sops:
    age:
        - recipient: age1a868fs5jjehx032kq7sryz3sjfzhkk79q2clqx8f4zawpfrlp9sswgr9fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBockZseWpMS1pVZUN4N1pz
            Y3BDVzBVekt6Q0NHS3lDQTFjKzFHS25vQ0FnCkxNZkpiM0NBUGxXQUgyQmhYNm5V
            bVhLdHRCNkFQMFhUaXkwdkZpaGtYREkKLS0tIHlhWDdJS0ZtcURLZ1lFbldtSDl1
            eFR0UmxtRDdHSXpSRGRRaDc4YmMzb1EKzAsBluTNp3//UHgrxxHTdtvEepY0DEmI
            h2bCa6XFXe/smOXPB3RVlTkm8DsWehR+T+4UcZ9cao3/8pWi2+JfXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v93l5pvd9pwlr9z04daa00wh2wan6ycu9ts8hn6p77gasgax256s6c6qg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRTk3QnBpVlNzSnlFRWQ5
            SXNvRFgrd3dxMjNNTUlwNTE5cHJLMTRYaUhBCjNDQkY3L05EWkFBMnp3b0s0MjNm
            eFdiK1MycG9hZGFId2gwWG5tUkh6NUUKLS0tIHlNYmpIL1NETllEeGFkYXdnSHhn
            ekRUMm5UcGR5Vno3bFdxMlcyVXdNQUEKV2uzm2ObSgNMS+NnN8QxU/xPZ9MydbZZ
            XK9VPmWXcNY/Hmk+bQinnvSVcmhe2EHQJ9OL32tlaBewb/BsXth1ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T14:11:35Z"
    mac: ENC[AES256_GCM,data:wUoYNmUn75x94cIwFZg5WyYzyeGlkvV3dy3Qf83ZlNNaJZd8nRTdLnMplDl+lLgQMPBBvrdsC81oriryC66b9k5dyUjfdwk1mLHRvHvknGdUPGlkcjPlAF1FXZ9fFUaV/vrH4CXk/QGqB7NJX9fDhl5RtiaBOsYUdJ2PaUGb5f8=,iv:1vuRRhCtfAbnho2SCF3HGZgf5pNcMQdXzIa9lcP8IkU=,tag:HvFuRO9U6RcpWr2us3NB2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
