wifi:
    network: ENC[AES256_GCM,data:0xomctEoMFHlI6vVFlQ=,iv:KlKLzFjnPVF5Dw8PY58hgHAlvDVM3QBvgVAYjH99rfQ=,tag:K4kC5Gwb88kNOl9n3shMHQ==,type:str]
    password: ENC[AES256_GCM,data:xhRVYEYlldepZo9Z,iv:qPBBxqNCPlx/BfrVFpoTiHvCDN0fRBcxuic4b1GY2Io=,tag:JJ2UsyCZik22ER1qdl7uCQ==,type:str]
passwd:
    alex: ENC[AES256_GCM,data:i4LouZjv/IqH+Vz23PgmfSGLx12MbSpniFI5oOQ3QzPlTDiVQpGqpPL3i53du/kFz1AWGSpb1orRiV0DsmhK1thnHafZn4nbZA==,iv:179w/hbHoIRLPLDFnPjckLLdErlRXTIelyQWLvK7Syo=,tag:K/R1wmJ3hRI+//iudE87yQ==,type:str]
caddy:
    adguard: ENC[AES256_GCM,data:o1jDM/bCsNkHej4ANt82+24J+yMEEY2XjO73ftIlz4iKnK+leJJyP4gdl2ZufEACmU+1qZJUOR0Zl6Wa,iv:ztI0e9nlP9L2Bb9nAhmuag4NKnyolayz/5ZAHQfXVEI=,tag:EfxExA3ICyClBw4/jZ75hg==,type:str]
    prefect: ENC[AES256_GCM,data:r0I61+fTEw0Rfru8c62Z/02n4TuXG1MlAqasrsyYjawxprASwA4LX+0Ul2fRGXhGa7KYFl7oc8R6KF0W,iv:Yj2XMpRNWNOOi1nfz7K+18aFQpMWrgWOmZJQ3GeU68c=,tag:F0vhudixKX20sABfUExsow==,type:str]
    torrent: ENC[AES256_GCM,data:iT6njnVhOJE2/tTo+fZzIq7LyYAEoNiE2pCul/B+QGT9QlDNoGOIgys05GRO8AqGY8wwYfA5DV92l+5r,iv:pLhbLWl8RoB5tcxL3kXJORf7MgQgVT19cEj64IX8ZbM=,tag:UWdzK3VRGaaR1Ul3/mHXnw==,type:str]
cloudflare:
    account: ENC[AES256_GCM,data:qsGo03tjuVL76bwKr+JbHBsdrzwtcs6bkFG5pi1JcnM=,iv:RcfBSw2EKic3N29WwLdA8uhmPnC/jfIRd7cSrLfHJs0=,tag:U4O58BlOJlHxsk7bKkQiqQ==,type:str]
    token: ENC[AES256_GCM,data:sPVAnXyYqG2+ztGbKNmn/SsmLiO61ktsFDjIWLjj59tJsvu7w3Q9yzyC+j48+nkl7PPoyFc=,iv:kVpwX1GFr+uLlk9TkCxExqgqX3CvdgQi9Cr2NdCBi+M=,tag:B2R2HMeR6wMl96QV1rq1Pw==,type:str]
mailjet:
    token: ENC[AES256_GCM,data:yz0s23KhpDpm6jeWkdlA+1yIrgG5SW426Jb5Zm0gDmQ=,iv:LBHOrgDzOCsYa5SXg19YqA+0Y5tsf9e9sUnsvxhKDec=,tag:Weeu4sUNkZXNjMfqynMTJQ==,type:str]
    secret: ENC[AES256_GCM,data:Xo78ubgVRhfvwX+BS5khTAkDB5Ok+7TCUd7DN5JqWKo=,iv:IiWl2eLP4pOMrnRLbsvyM6zfA7K2oqUK4mLpRAwW3Fw=,tag:3lcP2Kr5EFYHv/jHvtcjDA==,type:str]
nextcloud:
    admin: ENC[AES256_GCM,data:udFmxFPiE7tS46bjwdQt,iv:U6euyl9wfJ+hZ4M7wc8UCFSYxRp6Y+ajH1cz3xgzEt0=,tag:ctiHM0xZrEaM4W/cWjUWzg==,type:str]
nut:
    monitor: ENC[AES256_GCM,data:tni3G/yU2Z+dMp5Wfb4q,iv:RP7bUp6JrE2HP8XamaslQHYyK9VfydKW4bZlHtp+SnI=,tag:B9i4c3XcDm1mTJTctcsDpw==,type:str]
samba:
    alex: ENC[AES256_GCM,data:HECzGhVEwcXYtJWBzM3V,iv:uWwwiXiKVZo90W1+vo1BzSsc1+CmuQTN+MhOdpTL1Ek=,tag:MpJpCQAVD4zMBKflg0Qphg==,type:str]
umami:
    app-secret: ENC[AES256_GCM,data:LuiQbTn2aRFY9KytGl7LaDqLpOs=,iv:QAAU//WlEtl7cIZ6uwQRG/opBbunKK2Yw8RCdUcY8Uw=,tag:993LCXrR2tTq5w247VegEQ==,type:str]
wireguard:
    private-key: ENC[AES256_GCM,data:M3K1QdxHMHvVgsYkSKqjSt6TMpDSGKR03Qb+siWAYIypejhCHvQi1F4U+5o=,iv:YdN4tCEDYcMmg00GXMUk64JPLSNTdhNad2yeLCrxwhU=,tag:UL9Lu9br9WKiQ5iA2t/YaA==,type:str]
    psk:
        alex-laptop: ENC[AES256_GCM,data:sw2ezxylJosEpAXBgcAlmzfeFVaBhZLaXobEUBUnWIcCseJDq0rfS5DOKQc=,iv:QbQMTI1jVJK+XUmf+4JexXvaa+ebCAP4F299xmfxnQ8=,tag:PSp1vvS4rRWiqA4LtnXdDw==,type:str]
        alex-phone: ENC[AES256_GCM,data:SLG5hxfKZt/57jFsAlpyfNWPeTAOHRM4wHXXBthoAt9iD2Ex/HFc9zR/UBI=,iv:ePd6YShZqy3MdLgJGcjkiI8AQ70/GboAFws6LDEeeCs=,tag:YwUBZ1cpTrYLXQszuQa3ww==,type:str]
        alex-ipad: ENC[AES256_GCM,data:CMuiF9JFj8bk45wuC/LX6IZIuYbop6nzF3D+e4mXHmA9Fn9lknfx7tT1cdo=,iv:UH0i8xMiHLBoRKwV0JJAX/JwOXp9rPG5isB6OP3B8sE=,tag:8PXt7e9E5H6a0pMQ81yeuw==,type:str]
        mubin-laptop: ENC[AES256_GCM,data:R3gzXxdeSSnAz0x2lPb68OuvsvbQRwZuaaDGx2fFPnYiRFRrfPHjG8+LhbQ=,iv:40hiOM0SUKRkKHEPFiRAZQBmaH/WttZTzsGImujm1sQ=,tag:Y4em3aYa/YlMhhiwwRd3fQ==,type:str]
        mubin-phone-personal: ENC[AES256_GCM,data:cVwCqdqBGQ0IsZSkOj4knj+w7FsWK9v9b1hFOnkS/yGv2Z3r6kWawtZ2wio=,iv:xRwMAQ/2gLeP9hW0eadiUwLXvD1tNNm7eWUueHhx1gQ=,tag:R4SY5HYVX3pogb8oK9aK0Q==,type:str]
        mubin-phone-work: ENC[AES256_GCM,data:Jp0WzYUjcVELVjdDYOr8rOa7M72MPtICa9FTjaMDHMSjYQEaXRldxl53jvc=,iv:p6jLrmXLrS+v5MQitt+Tv1U3QOZ3FHyJkcnfsel8zWk=,tag:+yenCjwab6gzlb1+9yVNpw==,type:str]
wireguard-client:
    wgproton: ENC[AES256_GCM,data:+fOMQPYVTi/C5MeGKdlewWIm0iK/0pUqGSMDnHnSP5uMI3Q+y7AluIGvPjE=,iv:U8S3ul7TZEd08Z57F//Z+pD8RxY0S5540S0pJkhnZv8=,tag:vimx8w7durJ0m3ccGCsWIg==,type:str]
    wgproton-bt: ENC[AES256_GCM,data:urE2mtCM0eXitOjP/g++uN4l+syVmwfrSlYZ0MKooEl4lPpuVC60VPPL47Y=,iv:z5Z4trM0S+7tBbvXQAeZ9fm+N0q66rWsKqOCD7haQ8o=,tag:amVY4N40DbruH6qqkLS/oQ==,type:str]
sops:
    age:
        - recipient: age1a868fs5jjehx032kq7sryz3sjfzhkk79q2clqx8f4zawpfrlp9sswgr9fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBockZseWpMS1pVZUN4N1pz
            Y3BDVzBVekt6Q0NHS3lDQTFjKzFHS25vQ0FnCkxNZkpiM0NBUGxXQUgyQmhYNm5V
            bVhLdHRCNkFQMFhUaXkwdkZpaGtYREkKLS0tIHlhWDdJS0ZtcURLZ1lFbldtSDl1
            eFR0UmxtRDdHSXpSRGRRaDc4YmMzb1EKzAsBluTNp3//UHgrxxHTdtvEepY0DEmI
            h2bCa6XFXe/smOXPB3RVlTkm8DsWehR+T+4UcZ9cao3/8pWi2+JfXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v93l5pvd9pwlr9z04daa00wh2wan6ycu9ts8hn6p77gasgax256s6c6qg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRTk3QnBpVlNzSnlFRWQ5
            SXNvRFgrd3dxMjNNTUlwNTE5cHJLMTRYaUhBCjNDQkY3L05EWkFBMnp3b0s0MjNm
            eFdiK1MycG9hZGFId2gwWG5tUkh6NUUKLS0tIHlNYmpIL1NETllEeGFkYXdnSHhn
            ekRUMm5UcGR5Vno3bFdxMlcyVXdNQUEKV2uzm2ObSgNMS+NnN8QxU/xPZ9MydbZZ
            XK9VPmWXcNY/Hmk+bQinnvSVcmhe2EHQJ9OL32tlaBewb/BsXth1ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T13:55:18Z"
    mac: ENC[AES256_GCM,data:uZqAb/I0HtmDiJqhfEnrotE9Q3q0Ezsky73wNLQOWuxoKJmqa58SLi25H9R9pKVKyt/k2N8HTkp9cUP8T87d+Kw4qv+0BV341DE994EUvOcOoGemkZkQd+kCeRW9t9a+dnQBprjbFdFbrP6GKSsVl+P0Ify5Gyd3p75/HokFM2w=,iv:kPyXxJGkpipDDuaBh1dKDPiR4WfkS4QiD+XpX/Y2zAU=,tag:LH9FcBMpHyidwZE2i2jLDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
