wifi:
    network: ENC[AES256_GCM,data:0xomctEoMFHlI6vVFlQ=,iv:KlKLzFjnPVF5Dw8PY58hgHAlvDVM3QBvgVAYjH99rfQ=,tag:K4kC5Gwb88kNOl9n3shMHQ==,type:str]
    password: ENC[AES256_GCM,data:xhRVYEYlldepZo9Z,iv:qPBBxqNCPlx/BfrVFpoTiHvCDN0fRBcxuic4b1GY2Io=,tag:JJ2UsyCZik22ER1qdl7uCQ==,type:str]
passwd:
    alex: ENC[AES256_GCM,data:i4LouZjv/IqH+Vz23PgmfSGLx12MbSpniFI5oOQ3QzPlTDiVQpGqpPL3i53du/kFz1AWGSpb1orRiV0DsmhK1thnHafZn4nbZA==,iv:179w/hbHoIRLPLDFnPjckLLdErlRXTIelyQWLvK7Syo=,tag:K/R1wmJ3hRI+//iudE87yQ==,type:str]
caddy:
    adguard-hash: ENC[AES256_GCM,data:Lcic/8cWVZlR6UjJOAYDhow84kKOvKoRJbLxmJ0u9uHybCDsoSuwDMjZ1vE57jWaKMDN/BMxJsv65I+M,iv:iDeu6BVhwDTh6b2mOzUrCBc1EqnTYOWYogoh7vwpVw8=,tag:8T2WWx9x0nMOyBcqufE/aQ==,type:str]
    prefect-hash: ENC[AES256_GCM,data:OIoBwAIf5NSsLJZ3PBe/S3Uo239qvHHnxg9bJ8ubFzAnkVx/WFUC2T+xpP25GPC9WMiKuCUTH6/WAutZ,iv:S7dGm3KBHN3UOrS0sNwbBm43yRSPR9N+7AuQQiWVy/o=,tag:f3Hcu88Y6wwaYo5GUKoK8w==,type:str]
cloudflare:
    account: ENC[AES256_GCM,data:qsGo03tjuVL76bwKr+JbHBsdrzwtcs6bkFG5pi1JcnM=,iv:RcfBSw2EKic3N29WwLdA8uhmPnC/jfIRd7cSrLfHJs0=,tag:U4O58BlOJlHxsk7bKkQiqQ==,type:str]
    token: ENC[AES256_GCM,data:sPVAnXyYqG2+ztGbKNmn/SsmLiO61ktsFDjIWLjj59tJsvu7w3Q9yzyC+j48+nkl7PPoyFc=,iv:kVpwX1GFr+uLlk9TkCxExqgqX3CvdgQi9Cr2NdCBi+M=,tag:B2R2HMeR6wMl96QV1rq1Pw==,type:str]
mailjet:
    token: ENC[AES256_GCM,data:yz0s23KhpDpm6jeWkdlA+1yIrgG5SW426Jb5Zm0gDmQ=,iv:LBHOrgDzOCsYa5SXg19YqA+0Y5tsf9e9sUnsvxhKDec=,tag:Weeu4sUNkZXNjMfqynMTJQ==,type:str]
    secret: ENC[AES256_GCM,data:Xo78ubgVRhfvwX+BS5khTAkDB5Ok+7TCUd7DN5JqWKo=,iv:IiWl2eLP4pOMrnRLbsvyM6zfA7K2oqUK4mLpRAwW3Fw=,tag:3lcP2Kr5EFYHv/jHvtcjDA==,type:str]
nextcloud:
    admin-pass: ENC[AES256_GCM,data:wXpq8/f8WgPNjjowGTmU,iv:wSL+6GH6szmqAyUUibUeIBlMIUqWhnNDk4wRVEC6gK4=,tag:NPn5EfeQ0euI8QOpDlmgqQ==,type:str]
nut:
    monitor-password: ENC[AES256_GCM,data:60svJqgP+PCTLvxXexzZ,iv:h99PpMN5VdEGkfVmuVFduDIZoLt5fvCzA6UKo2Bm1Mg=,tag:kT7N0hJz78ltGW8EzUPSYw==,type:str]
umami:
    app-secret: ENC[AES256_GCM,data:LuiQbTn2aRFY9KytGl7LaDqLpOs=,iv:QAAU//WlEtl7cIZ6uwQRG/opBbunKK2Yw8RCdUcY8Uw=,tag:993LCXrR2tTq5w247VegEQ==,type:str]
wireguard:
    privatekey: ENC[AES256_GCM,data:03r2uRklUzztYcNBXzhf3T0hQJ9yy/3ZqGxwW3f4oCQFrAal7QY3w+FMIZE=,iv:6Gps7nxveJrNvFrOa09BjB69a1p1Ef0akaadaRTzZB0=,tag:HxlYta9+2m+CzIq25skS1g==,type:str]
sops:
    age:
        - recipient: age1a868fs5jjehx032kq7sryz3sjfzhkk79q2clqx8f4zawpfrlp9sswgr9fl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBockZseWpMS1pVZUN4N1pz
            Y3BDVzBVekt6Q0NHS3lDQTFjKzFHS25vQ0FnCkxNZkpiM0NBUGxXQUgyQmhYNm5V
            bVhLdHRCNkFQMFhUaXkwdkZpaGtYREkKLS0tIHlhWDdJS0ZtcURLZ1lFbldtSDl1
            eFR0UmxtRDdHSXpSRGRRaDc4YmMzb1EKzAsBluTNp3//UHgrxxHTdtvEepY0DEmI
            h2bCa6XFXe/smOXPB3RVlTkm8DsWehR+T+4UcZ9cao3/8pWi2+JfXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v93l5pvd9pwlr9z04daa00wh2wan6ycu9ts8hn6p77gasgax256s6c6qg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRTk3QnBpVlNzSnlFRWQ5
            SXNvRFgrd3dxMjNNTUlwNTE5cHJLMTRYaUhBCjNDQkY3L05EWkFBMnp3b0s0MjNm
            eFdiK1MycG9hZGFId2gwWG5tUkh6NUUKLS0tIHlNYmpIL1NETllEeGFkYXdnSHhn
            ekRUMm5UcGR5Vno3bFdxMlcyVXdNQUEKV2uzm2ObSgNMS+NnN8QxU/xPZ9MydbZZ
            XK9VPmWXcNY/Hmk+bQinnvSVcmhe2EHQJ9OL32tlaBewb/BsXth1ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T18:30:44Z"
    mac: ENC[AES256_GCM,data:DoNlhF9JrYe+kgTixESAKqCeQNWLVd41hZOp3LZ8UfLww49zDPc6QFFIdIcG2YNPeoVJ9hlu9/vI9uQlyJ55nhZ9ijwH8h2hbW/GygvALKO9dvTe/XHW0sYTd5N/lVq7nlzrhl5T9eeTO7d0/v5yebYmiHdOnEjSzPltXyc37EU=,iv:mgDGmf6RVJItlH6Bpb4A4IwQEOcNHzs1arht58vFsSI=,tag:iAk81M1ljuXs9+i798AZjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
