# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "tpm_crb" "tpm_tis" ];
  boot.extraModulePackages = [ ];

  fileSystems = {

    "/" = {
      device = "/dev/disk/by-uuid/851be909-0cca-43a0-83c2-a36e353c28a5";
      fsType = "ext4";
      options = [ "noatime" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/AA54-7CAB";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    # Both of these carry service state (nextcloud, immich, vaultwarden,
    # postgresql, bitcoind, prefect, the media shares) that systemd-tmpfiles has
    # rules for, so tmpfiles MUST NOT run before they are mounted.
    #
    # It did. `nofail` keeps a missing disk from wedging the boot, but it also
    # drops the mount out of `local-fs.target`'s ordering — and
    # systemd-tmpfiles-setup.service is only `After=local-fs.target`, so it stops
    # waiting for these. Measured on the 2026-09-19 boot: tmpfiles ran at
    # 01:18:05, srv-encrypted.mount became active at 01:18:20, fifteen seconds
    # later. Every rule under these paths therefore applied to the empty stub
    # directory UNDERNEATH the mountpoint, which the real filesystem then hid:
    # ownership and modes silently never reached the actual directories, and an
    # `L+` symlink written there is invisible the moment the disk mounts over it.
    #
    # `x-systemd.before=` orders WITHOUT requiring, which is the distinction that
    # matters here: tmpfiles waits for the mount to be attempted, but a disk that
    # never shows up still cannot fail the boot, so `nofail` keeps its meaning.
    # Safe against hangs because the unlock is unattended — crypttab uses
    # tpm2-device=auto, so nothing waits on a passphrase.
    "/srv" = {
      device = "/dev/disk/by-uuid/20240caa-cc06-4e97-8537-1a1ae9e617ba";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "nofail" "x-systemd.before=systemd-tmpfiles-setup.service" ];
    };

    "/srv/encrypted" = {
      device = "/dev/mapper/srv-encrypted";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "nofail" "x-systemd.before=systemd-tmpfiles-setup.service" ];
    };

  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/202a4b1e-41cd-4196-95b6-6af91735898e"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
