github-token: ENC[AES256_GCM,data:4dzARxVdvJb8vjfo7JRBMNbQuiKf/Sb3MGhTFpoPZR02oy+wGUnphQ==,iv:zLxahcIJXkutJ7aQ+VATlAXZwqqWWzMF5Gh4O5MbHz0=,tag:EWvrSSm8+dLZbuo+hD5UDA==,type:str]
sops:
    age:
        - recipient: age14lrzcnp08aawpzz2vcvgprkxv7yc7cpah5ep7fh2n8nne06jucfs98r6e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydGRFN1lzOEFTbEJJU0RW
            SnNmaEdHZk51S05PbGlUVHNaSHl5RHNVMWlrCkdDN3UrZ3Q5WU9USlRINnVVWHJS
            VHNBM3NGeDFMT2g0UVBhekpLUjNKb1UKLS0tIC9EcTJaZnBDcnRLRXIrNjV1eldk
            RGFmL1plSzVkRmtYMG4vRlpRT0t2MXcK9AlllxniK4dxZP/2jAU68I4x2twFTWVv
            8aR7bEE8yO7nmO1G2Ujn408ZhsmMCEtdzLw+ZLmR8qau1gHcACb/jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T20:21:08Z"
    mac: ENC[AES256_GCM,data:jJLmygR9FtedwEHSpabLaG7pjm94ydABcj20I4UQmmYQWq8/SOE1WHmeLltnXqhImYo98bsqb03SfnatKtxSfAwF7GGrlohK9jmM3Qnc28IzvYDOfZZVNpacTzklMFq3H4FoIGwkXaWgmJH0HBF+94j0Iqb93JQ+deer8J1A9Is=,iv:k+yv9oK3ZHd1eHPneo45LMurezObCRlegtETxsK929s=,tag:imwvIAr4EbfJLxl5j1y7XQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
